#!/usr/bin/sudo bash

./buildshared

declare -a arr=("memoria" "cpu" "kernel" "consola")

## now loop through the above array
for i in "${arr[@]}"
do
    ./build $i
    rm -rf "$i/Debug/$i.log"
    if [ $? -ne 0 ]; then
        exit 1
    fi
done