#!/usr/bin/sudo bash

CONFIG="default"
MODULO=""

CYAN='\033[0;36m'
RED='\033[0;31m'
NC='\033[0m'

killall terminator

while test $# -gt 0
do
  CONFIG="default"
  MODULO=$1

  shift

  if [ -d "config/$1" ]; then
    CONFIG=$1
    shift
  fi

  echo -e "Abirendo terminal para $CYAN$MODULO$NC con config $CYAN$CONFIG$NC"
  terminator --geometry 960 --title $MODULO  -e "./run $MODULO $CONFIG; bash" &
  sleep 1s

done


